title: Fugue Tutorials
logo: images/logo_blue.svg
execute:
  execute_notebooks: off
  allow_errors: false

launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  thebe                     : false 

repository:
  url                       : https://github.com/fugue-project/tutorials  # The URL to your book's repository
  path_to_book              : ""  # A path to your book's folder, relative to the repository root.
  branch                    : master  # Which branch of the repository should be used when creating links

