name: fugue-docs
channels:
  - conda-forge
  - defaults
dependencies:
  
  # docs
  - jupyter-book

  # notebook dependencies
  - pandas
  - dask
  - pyspark
  - dask-sql
  - scikit-learn  

  # fugue dependencies
  - triad
  - adagio
  - werkzeug
  - six
  - ciso8601
  - fs

  - pip
  - pip:
    - fugue